songe = [
	muz_one = [0, 'Carriage - contrasting dark red', 'media/QQQQ/contrasting_dark_red.mp3','113', 'img/covers/QQQQ.jpg'],
	muz_two = [1, 'Carriage - BROKEN DISPLAYS', 'media/QQQQ/BROKEN_DISPLAYS.mp3','156', 'img/covers/QQQQ.jpg'],
	muz_free = [2, 'Carriage - 37.7 (so very highly much deep song yo)', 'media/QQQQ/37.7_(so_very_highly_much_deep_song_yo).mp3','147.6', 'img/covers/QQQQ.jpg'],
	muz_four = [3, 'Carriage - I`M SO HIGH', 'media/QQQQ/I`M_SO_HIGH.mp3','150.5', 'img/covers/QQQQ.jpg'],
	muz_five = [4, 'Carriage - FINGER CROSS pt.2', 'media/QQQQ/FINGER_CROSS_pt.2.mp3','205.5', 'img/covers/QQQQ.jpg'],
	muz_six = [5, 'Carriage - i tropinka, i lesok', 'media/QQQQ/i_tropinka_i_lesok.mp3','198.5', 'img/covers/QQQQ.jpg'],
	muz_seven = [6, 'Carriage - deaf listeners without ears love us', 'media/QQQQ/deaf_listeners_without_ears_love_us_so_we_love_them_too.mp3','140.7', 'img/covers/QQQQ.jpg'],
	muz_eight = [7, 'Carriage - whose vintage copybook here', 'media/QQQQ/whose_vintage_copybook_here.mp3','229.5', 'img/covers/QQQQ.jpg'],
	muz_nine = [8, 'Carriage - weeded autumn (ft. rd22.10)', 'media/QQQQ/weeded_autumn_(ft. rd22.10).mp3','180.1', 'img/covers/QQQQ.jpg'],
	muz_ten = [9, 'Carriage - sufferer (ft. wet cat)', 'media/QQQQ/sufferer_(ft. wet cat).mp3','144.1', 'img/covers/QQQQ.jpg'],
	muz_eleven = [10, 'Carriage - you should', 'media/QQQQ/you_should.mp3','153.2', 'img/covers/QQQQ.jpg'],
	muz_twelve = [11, 'Carriage - feel it', 'media/QQQQ/feel_it.mp3','147.5', 'img/covers/QQQQ.jpg'],
	muz_thirteen = [12, 'Carriage - slower and slower', 'media/QQQQ/slower_and_slower.mp3','138.9', 'img/covers/QQQQ.jpg'],
];